"""prueba de migracion

Revision ID: 36c686e2e1b7
Revises: aa7cdb9187ca
Create Date: 2026-08-24 09:14:26.749628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c686e2e1b7'
down_revision: Union[str, Sequence[str], None] = 'aa7cdb9187ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('fecha2', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fecha2')
    # ### end Alembic commands ###
